//! Static Vocabulary Data
//!
//! Contains all static vocabulary lists for TTRPG content classification:
//! - Genres and character classes/roles by genre
//! - Races and species by setting type
//! - System-specific terminology (D&D, PF2e, CoC, etc.)
//! - Content category indicators
//! - Equipment lists
//! - Character traits
//! - Publishers

use once_cell::sync::Lazy;

// ============================================================================
// GENRES
// ============================================================================

/// Primary TTRPG genres for content classification
pub static GENRES: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "fantasy",
        "science fiction",
        "horror",
        "cosmic horror",
        "modern horror",
        "cyberpunk",
        "post-apocalyptic",
        "steampunk",
        "urban fantasy",
        "dark fantasy",
        "high fantasy",
        "low fantasy",
        "grimdark",
        "sword and sorcery",
        "space opera",
        "military sci-fi",
        "western",
        "pulp",
        "noir",
        "supernatural",
        "historical",
        "alternate history",
        "supers",
        "superhero",
    ]
});

// ============================================================================
// CHARACTER CLASSES BY GENRE
// ============================================================================

/// Fantasy character classes
pub static FANTASY_CLASSES: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "barbarian",
        "bard",
        "cleric",
        "druid",
        "fighter",
        "monk",
        "paladin",
        "ranger",
        "rogue",
        "sorcerer",
        "warlock",
        "wizard",
        "artificer",
        "knight",
        "thief",
        "assassin",
        "necromancer",
        "illusionist",
        "conjurer",
        "diviner",
        "enchanter",
        "evoker",
        "transmuter",
        "abjurer",
        "bladesinger",
        "eldritch knight",
        "arcane trickster",
        "champion",
        "battle master",
        "cavalier",
        "samurai",
        "kensei",
        "swashbuckler",
        "inquisitor",
        "oracle",
        "witch",
        "magus",
        "gunslinger",
        "alchemist",
        "investigator",
        "summoner",
        "kineticist",
    ]
});

/// Sci-fi character classes/roles
pub static SCIFI_CLASSES: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "soldier",
        "engineer",
        "scientist",
        "pilot",
        "medic",
        "hacker",
        "operative",
        "diplomat",
        "merchant",
        "bounty hunter",
        "smuggler",
        "technician",
        "psion",
        "mechanic",
        "scout",
        "marine",
        "navigator",
        "gunner",
        "captain",
        "commodore",
        "envoy",
        "mystic",
        "solarian",
    ]
});

/// Horror character archetypes
pub static HORROR_CLASSES: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "investigator",
        "antiquarian",
        "author",
        "dilettante",
        "doctor",
        "journalist",
        "lawyer",
        "librarian",
        "military officer",
        "nurse",
        "parapsychologist",
        "photographer",
        "police detective",
        "priest",
        "private eye",
        "professor",
        "psychologist",
        "scientist",
        "soldier",
        "spy",
        "student",
        "tribal member",
        "zealot",
        "drifter",
        "entertainer",
        "federal agent",
        "clergy",
        "alienist",
        "archeologist",
        "athlete",
    ]
});

/// Modern/contemporary character types
pub static MODERN_CLASSES: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "street samurai",
        "decker",
        "rigger",
        "face",
        "mage",
        "shaman",
        "adept",
        "technomancer",
        "infiltrator",
        "wheelman",
        "fixer",
        "cleaner",
        "hitter",
        "hacker",
        "thief",
        "mastermind",
        "driver",
        "muscle",
        "grifter",
        "researcher",
        "reporter",
        "cop",
        "agent",
    ]
});

// ============================================================================
// RACES AND SPECIES
// ============================================================================

/// Fantasy races
pub static FANTASY_RACES: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "human",
        "elf",
        "dwarf",
        "halfling",
        "gnome",
        "half-elf",
        "half-orc",
        "tiefling",
        "dragonborn",
        "aasimar",
        "genasi",
        "goliath",
        "tabaxi",
        "kenku",
        "firbolg",
        "triton",
        "yuan-ti",
        "bugbear",
        "goblin",
        "hobgoblin",
        "kobold",
        "orc",
        "lizardfolk",
        "tortle",
        "aarakocra",
        "warforged",
        "changeling",
        "shifter",
        "kalashtar",
        "leonin",
        "satyr",
        "fairy",
        "harengon",
        "owlin",
        "dhampir",
        "hexblood",
        "reborn",
        "autognome",
        "giff",
        "hadozee",
        "plasmoid",
        "thri-kreen",
    ]
});

/// Sci-fi species
pub static SCIFI_RACES: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "android",
        "cyborg",
        "alien",
        "mutant",
        "clone",
        "uplifted",
        "synthetic",
        "vat-grown",
        "gene-modified",
        "transhuman",
        "posthuman",
        "vesk",
        "ysoki",
        "lashunta",
        "shirren",
        "kasatha",
        "skittermander",
        "vlaka",
        "asari",
        "turian",
        "salarian",
        "krogan",
    ]
});

// ============================================================================
// SYSTEM-SPECIFIC TERMS
// ============================================================================

/// D&D 5e specific terms for detection
pub static DND5E_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "5th edition",
        "5e",
        "advantage",
        "disadvantage",
        "proficiency bonus",
        "ability check",
        "saving throw",
        "attack roll",
        "spell slot",
        "cantrip",
        "concentration",
        "bonus action",
        "reaction",
        "initiative",
        "hit points",
        "armor class",
        "difficulty class",
        "dc",
        "d20",
        "multiclass",
        "subclass",
        "background",
        "feat",
        "inspiration",
        "exhaustion",
        "short rest",
        "long rest",
        "attunement",
        "legendary action",
        "lair action",
        "legendary resistance",
        "death saving throw",
        "critical hit",
        "natural 20",
        "nat 20",
        "bardic inspiration",
        "sneak attack",
        "divine smite",
        "wild shape",
        "rage",
        "ki points",
        "sorcery points",
        "warlock patron",
        "eldritch invocation",
        "fighting style",
        "channel divinity",
        "action surge",
        "second wind",
    ]
});

/// Pathfinder 2e specific terms
pub static PF2E_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "pathfinder 2e",
        "pf2e",
        "2nd edition",
        "three-action economy",
        "activity",
        "free action",
        "reaction",
        "condition",
        "trait",
        "ancestry",
        "heritage",
        "class feat",
        "skill feat",
        "general feat",
        "ancestry feat",
        "archetype",
        "dedication",
        "spell heightening",
        "incapacitation",
        "minion",
        "summoned",
        "persistent damage",
        "golarion",
        "inner sea",
        "absalom",
        "lost omens",
        "age of lost omens",
        "starstone",
        "pathfinder society",
        "critical specialization",
        "recall knowledge",
        "action economy",
        "degree of success",
        "hero point",
        "encounter mode",
        "exploration mode",
        "downtime mode",
    ]
});

/// Call of Cthulhu specific terms
pub static COC_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "call of cthulhu",
        "coc",
        "7th edition",
        "7e",
        "keeper",
        "mythos",
        "sanity",
        "sanity check",
        "san",
        "san loss",
        "indefinite insanity",
        "temporary insanity",
        "bout of madness",
        "phobia",
        "mania",
        "luck",
        "luck roll",
        "pushed roll",
        "bonus die",
        "penalty die",
        "hard success",
        "extreme success",
        "fumble",
        "impale",
        "major wound",
        "hit location",
        "occupation",
        "credit rating",
        "cthulhu mythos",
        "mythos tome",
        "spell",
        "elder sign",
        "elder thing",
        "great old one",
        "outer god",
        "deep one",
        "shoggoth",
        "mi-go",
        "yithian",
        "byakhee",
        "dimensional shambler",
        "hound of tindalos",
        "nightgaunt",
        "ghoul",
        "lovecraft",
        "lovecraftian",
        "cosmic horror",
        "cultist",
        "cult",
    ]
});

/// Delta Green specific terms
pub static DELTA_GREEN_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "delta green",
        "dg",
        "handler",
        "agent",
        "cell",
        "program",
        "opera",
        "night at the opera",
        "the program",
        "the outlaws",
        "majestic-12",
        "mj-12",
        "phenomen-x",
        "march technologies",
        "saucerwatch",
        "bond",
        "bonds",
        "sanity",
        "breaking point",
        "adapted",
        "hardened",
        "projection",
        "home",
        "ritual",
        "unnatural",
        "willpower",
        "violence",
        "helplessness",
        "san loss",
        "federal agent",
        "green box",
        "operation",
        "need to know",
        "case officer",
        "friendly",
        "the thing",
        "karotechia",
        "gru sv-8",
        "pisces",
        "project rainbow",
        "working group",
    ]
});

/// Blades in the Dark specific terms
pub static BITD_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "blades in the dark",
        "bitd",
        "forged in the dark",
        "fitd",
        "doskvol",
        "duskwall",
        "duskvol",
        "ghost",
        "spirit",
        "demon",
        "leviathan",
        "electroplasm",
        "ghost field",
        "deathseeker crow",
        "score",
        "crew",
        "claim",
        "turf",
        "heat",
        "wanted level",
        "tier",
        "hold",
        "rep",
        "coin",
        "stash",
        "stress",
        "trauma",
        "harm",
        "resistance roll",
        "action roll",
        "fortune roll",
        "effect",
        "position",
        "controlled",
        "risky",
        "desperate",
        "devil's bargain",
        "flashback",
        "load",
        "downtime",
        "entanglement",
        "faction",
        "assassin",
        "bravos",
        "cult",
        "hawkers",
        "shadows",
        "smugglers",
        "cutter",
        "hound",
        "leech",
        "lurk",
        "slide",
        "spider",
        "whisper",
    ]
});

/// Savage Worlds specific terms
pub static SAVAGE_WORLDS_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "savage worlds",
        "swade",
        "adventure edition",
        "bennies",
        "benny",
        "wild die",
        "ace",
        "exploding dice",
        "raise",
        "wound",
        "shaken",
        "incapacitated",
        "soak roll",
        "edges",
        "hindrances",
        "trait",
        "attribute",
        "skill",
        "wild card",
        "extra",
        "power points",
        "arcane background",
        "deadlands",
        "rippers",
        "east texas university",
        "interface zero",
        "pinnacle",
        "fast furious fun",
        "test of wills",
        "agility trick",
        "smarts trick",
        "gang up",
        "support",
    ]
});

/// FATE specific terms
pub static FATE_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "fate",
        "fate core",
        "fate accelerated",
        "fae",
        "fate condensed",
        "aspect",
        "invoke",
        "compel",
        "fate point",
        "refresh",
        "stunt",
        "approach",
        "skill",
        "stress",
        "consequence",
        "concession",
        "taken out",
        "boost",
        "situation aspect",
        "character aspect",
        "high concept",
        "trouble",
        "phase trio",
        "bronze rule",
        "fate fractal",
        "four actions",
        "overcome",
        "create advantage",
        "attack",
        "defend",
        "shift",
        "ladder",
        "fudge dice",
        "fate dice",
    ]
});

/// Powered by the Apocalypse terms
pub static PBTA_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "powered by the apocalypse",
        "pbta",
        "move",
        "basic move",
        "playbook",
        "mc",
        "master of ceremonies",
        "hard move",
        "soft move",
        "hit",
        "miss",
        "partial success",
        "7-9",
        "10+",
        "6-",
        "hold",
        "forward",
        "ongoing",
        "apocalypse world",
        "dungeon world",
        "monster of the week",
        "masks",
        "urban shadows",
        "monsterhearts",
        "the sprawl",
        "impulse drive",
        "harm",
        "countdown",
        "front",
        "threat",
        "agenda",
        "principles",
    ]
});

/// Mothership specific terms
pub static MOTHERSHIP_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "mothership",
        "0e",
        "1e",
        "sci-fi horror",
        "stress",
        "panic check",
        "panic table",
        "android",
        "scientist",
        "teamster",
        "marine",
        "warden",
        "player's survival guide",
        "dead planet",
        "gradient descent",
        "pound of flesh",
        "hull breach",
        "vacuum",
        "hyperspace",
        "cryosleep",
        "company",
        "corporate",
        "colonial marines",
    ]
});

/// Traveller specific terms
pub static TRAVELLER_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "traveller",
        "mongoose traveller",
        "2d6",
        "career",
        "term",
        "mustering out",
        "characteristic",
        "skill check",
        "task chain",
        "jump drive",
        "jump space",
        "parsec",
        "starport",
        "trade goods",
        "patron",
        "starship",
        "spacecraft",
        "ship share",
        "cr",
        "credits",
        "imperium",
        "third imperium",
        "spinward marches",
        "solomani",
        "vilani",
        "zhodani",
        "vargr",
        "aslan",
        "subsector",
        "sector",
        "world profile",
        "uwp",
        "tech level",
        "law level",
        "government type",
    ]
});

/// GURPS specific terms
pub static GURPS_TERMS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "gurps",
        "generic universal",
        "steve jackson games",
        "3d6",
        "character points",
        "advantages",
        "disadvantages",
        "quirks",
        "skills",
        "techniques",
        "default",
        "attribute",
        "secondary characteristic",
        "active defense",
        "dodge",
        "parry",
        "block",
        "damage resistance",
        "hit points",
        "fatigue points",
        "basic speed",
        "basic move",
        "reaction modifier",
        "tech level",
        "magic system",
        "psionic",
    ]
});

// ============================================================================
// CONTENT CATEGORIES
// ============================================================================

/// Indicators for rulebook content
pub static RULEBOOK_INDICATORS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "rules",
        "mechanics",
        "character creation",
        "ability scores",
        "combat",
        "spellcasting",
        "equipment",
        "skills",
        "feats",
        "classes",
        "races",
        "leveling",
        "advancement",
        "actions",
        "conditions",
        "saving throws",
        "difficulty class",
        "modifier",
        "proficiency",
        "multiclassing",
        "prerequisites",
        "chapter",
        "core rules",
        "basic rules",
        "advanced rules",
        "optional rules",
        "variant rules",
        "house rules",
        "errata",
        "clarification",
    ]
});

/// Indicators for adventure/scenario content
pub static ADVENTURE_INDICATORS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "adventure",
        "scenario",
        "module",
        "campaign",
        "quest",
        "mission",
        "hook",
        "encounter",
        "scene",
        "act",
        "chapter",
        "epilogue",
        "prologue",
        "read aloud",
        "boxed text",
        "handout",
        "player handout",
        "map",
        "dungeon",
        "location",
        "npc",
        "villain",
        "boss",
        "treasure",
        "reward",
        "loot",
        "experience points",
        "xp",
        "random encounter",
        "wandering monster",
        "investigation",
    ]
});

/// Indicators for bestiary/monster content
pub static BESTIARY_INDICATORS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "monster",
        "creature",
        "beast",
        "stat block",
        "challenge rating",
        "cr",
        "hit dice",
        "hd",
        "armor class",
        "ac",
        "attack",
        "damage",
        "special abilities",
        "legendary actions",
        "lair actions",
        "legendary resistance",
        "traits",
        "actions",
        "reactions",
        "bestiary",
        "monster manual",
        "creature catalog",
        "enemies",
        "adversaries",
        "npc stats",
        "minion",
        "elite",
        "solo",
    ]
});

/// Indicators for setting/worldbuilding content
pub static SETTING_INDICATORS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "setting",
        "world",
        "campaign setting",
        "gazetteer",
        "atlas",
        "geography",
        "history",
        "timeline",
        "culture",
        "society",
        "religion",
        "pantheon",
        "deity",
        "god",
        "goddess",
        "faction",
        "organization",
        "guild",
        "nation",
        "kingdom",
        "empire",
        "city",
        "town",
        "village",
        "region",
        "continent",
        "plane",
        "realm",
        "cosmology",
        "calendar",
        "economy",
        "politics",
        "law",
    ]
});

/// Indicators for player options content
pub static PLAYER_OPTIONS_INDICATORS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "player option",
        "character option",
        "new class",
        "new subclass",
        "new race",
        "new ancestry",
        "new feat",
        "new spell",
        "new item",
        "magic item",
        "artifact",
        "equipment",
        "weapon",
        "armor",
        "background",
        "archetype",
        "prestige class",
        "paragon path",
        "epic destiny",
        "playbook",
        "specialization",
        "talent tree",
    ]
});

// ============================================================================
// PUBLISHERS
// ============================================================================

/// Known TTRPG publishers
pub static PUBLISHERS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "wizards of the coast",
        "wotc",
        "paizo",
        "chaosium",
        "arc dream",
        "arc dream publishing",
        "evil hat",
        "evil hat productions",
        "pinnacle entertainment",
        "pinnacle entertainment group",
        "peg",
        "free league",
        "free league publishing",
        "modiphius",
        "modiphius entertainment",
        "monte cook games",
        "mcg",
        "pelgrane press",
        "steve jackson games",
        "sjg",
        "fantasy flight games",
        "ffg",
        "cubicle 7",
        "r. talsorian games",
        "green ronin",
        "green ronin publishing",
        "kobold press",
        "tuesday knight games",
        "magpie games",
        "onyx path",
        "onyx path publishing",
        "white wolf",
        "renegade game studios",
        "goodman games",
    ]
});

// ============================================================================
// EQUIPMENT
// ============================================================================

/// Common weapon types
pub static WEAPONS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "sword",
        "longsword",
        "shortsword",
        "greatsword",
        "rapier",
        "scimitar",
        "dagger",
        "knife",
        "axe",
        "battleaxe",
        "greataxe",
        "handaxe",
        "mace",
        "morningstar",
        "flail",
        "warhammer",
        "maul",
        "club",
        "staff",
        "quarterstaff",
        "spear",
        "javelin",
        "trident",
        "halberd",
        "glaive",
        "pike",
        "lance",
        "whip",
        "bow",
        "longbow",
        "shortbow",
        "crossbow",
        "light crossbow",
        "heavy crossbow",
        "hand crossbow",
        "sling",
        "dart",
        "blowgun",
        "net",
        "pistol",
        "rifle",
        "shotgun",
        "submachine gun",
        "assault rifle",
        "sniper rifle",
        "laser",
        "plasma",
        "blaster",
        "beam weapon",
        "energy weapon",
    ]
});

/// Common armor types
pub static ARMOR: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "leather armor",
        "studded leather",
        "hide armor",
        "chain shirt",
        "chain mail",
        "chainmail",
        "scale mail",
        "breastplate",
        "half plate",
        "plate armor",
        "full plate",
        "shield",
        "buckler",
        "helmet",
        "helm",
        "gauntlet",
        "greaves",
        "vambrace",
        "padded armor",
        "ring mail",
        "splint armor",
        "flak jacket",
        "kevlar",
        "body armor",
        "power armor",
        "combat armor",
        "vacc suit",
        "environmental suit",
        "hardsuit",
    ]
});

// ============================================================================
// CHARACTER TRAITS
// ============================================================================

/// Common character motivations
pub static MOTIVATIONS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "revenge",
        "redemption",
        "glory",
        "wealth",
        "power",
        "knowledge",
        "justice",
        "freedom",
        "protection",
        "discovery",
        "survival",
        "fame",
        "legacy",
        "duty",
        "honor",
        "love",
        "loyalty",
        "faith",
        "curiosity",
        "ambition",
        "escape",
        "belonging",
        "identity",
    ]
});

/// Common character backgrounds
pub static BACKGROUNDS: Lazy<Vec<&'static str>> = Lazy::new(|| {
    vec![
        "acolyte",
        "charlatan",
        "criminal",
        "entertainer",
        "folk hero",
        "guild artisan",
        "hermit",
        "noble",
        "outlander",
        "sage",
        "sailor",
        "soldier",
        "urchin",
        "spy",
        "pirate",
        "knight",
        "gladiator",
        "haunted one",
        "far traveler",
        "inheritor",
        "mercenary veteran",
        "city watch",
        "clan crafter",
        "cloistered scholar",
        "courtier",
        "faction agent",
        "marine",
        "shipwright",
        "smuggler",
        "urban bounty hunter",
    ]
});
